# Generated by Django 2.2.12 on 2022-11-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0005_auto_20221108_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='课件')),
                ('file_name', models.CharField(blank=True, default=None, max_length=64, verbose_name='课件名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_course', to='baweb.Course', verbose_name='所属课程')),
            ],
        ),
    ]
