# Generated by Django 3.2.25 on 2025-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baweb', '0022_post_forum_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='baweb_post_course_heat_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='baweb_post_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='baweb_post_author_idx',
        ),
        migrations.RemoveIndex(
            model_name='postcomment',
            name='baweb_postcomment_post_idx',
        ),
        migrations.RemoveIndex(
            model_name='postcomment',
            name='baweb_postcomment_author_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['course', '-heatScore'], name='baweb_post_course__e37517_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-createdAt'], name='baweb_post_created_d532a7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='baweb_post_author__9b7543_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', '-createdAt'], name='baweb_postc_post_id_881dec_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['author'], name='baweb_postc_author__5cfea4_idx'),
        ),
    ]
